name = "suggest"
main = "index.js"
compatibility_date = "2025-06-01"

[vars]
REPO = "allvei/bigwalk-speedrun-guide"
BRANCH = "main"
UPLOAD_BRANCH = "suggestions"
ALLOWED_ORIGINS = "https://allvei.github.io,https://guide.bigwalk.workers.dev"
GITHUB_CLIENT_ID = "Ov23likbfD99J8sbGlXi"
